#!/usr/bin/env node
// Generate D2 from an honest-arch-diagrams model.
// Zero dependencies.
//
// Usage:
//   node scripts/to-d2.mjs <model.json> [--out <file.d2>]

import { readFileSync, writeFileSync } from 'node:fs';

const ACCENT = '#2563eb';
const d2Id = (id) => String(id).replace(/[^a-zA-Z0-9_]/g, '_');
const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const companionBand = (c) => {
  if (c.kind === 'db' || c.kind === 'cloud') return 'Data';
  if (c.kind === 'auth') return 'Identity';
  return 'App';
};

/** Build a D2 document from a parsed model. */
export function toD2(model) {
  const lines = [];
  lines.push(`# Honest request-path diagram for \`${model.app}\`.`);
  lines.push('# Generated by scripts/to-d2.mjs — accent marks ONLY the verified path.');
  lines.push('');
  lines.push('direction: right');
  lines.push('');
  lines.push('vars: {');
  lines.push(`  accent: "${ACCENT}"`);
  lines.push('}');
  lines.push('');

  const linked = (model.companions ?? []).filter((c) => c.relation === 'linked');
  const around = (model.companions ?? []).filter((c) => c.relation === 'around');

  const nodesByLane = new Map();
  for (const h of model.hops ?? []) {
    (nodesByLane.get(h.lane) ?? nodesByLane.set(h.lane, []).get(h.lane)).push({
      id: h.id, label: h.label, dashed: false,
    });
  }
  for (const c of linked) {
    const band = companionBand(c);
    (nodesByLane.get(band) ?? nodesByLane.set(band, []).get(band)).push({
      id: c.id, label: c.label, dashed: true,
    });
  }

  const laneOrder = ['Edge', 'Gateway', 'Identity', 'App', 'Workload', 'Data'];
  for (const lane of laneOrder) {
    const nodes = nodesByLane.get(lane);
    if (!nodes?.length) continue;
    lines.push(`${lane}: ${lane} {`);
    for (const n of nodes) {
      lines.push(`  ${d2Id(n.id)}: "${esc(n.label)}"`);
      if (n.dashed) lines.push(`  ${d2Id(n.id)}.style.stroke-dash: 3`);
    }
    lines.push('}');
    lines.push('');
  }

  const pathEdges = (model.edges ?? []).filter((e) => e.path);
  if (pathEdges.length) {
    const hopById = new Map((model.hops ?? []).map((h) => [h.id, h]));
    const next = new Map(pathEdges.map((e) => [e.from, e.to]));
    const targets = new Set(pathEdges.map((e) => e.to));
    let start = pathEdges.map((e) => e.from).find((id) => !targets.has(id)) ?? pathEdges[0].from;
    const chain = [start];
    while (next.has(chain.at(-1)) && chain.length <= pathEdges.length + 1) {
      chain.push(next.get(chain.at(-1)));
    }
    const parts = chain
      .map((id) => hopById.get(id))
      .filter(Boolean)
      .map((h) => `${h.lane}.${d2Id(h.id)}`);
    if (parts.length >= 2) {
      lines.push(`${parts.join(' -> ')}: {`);
      lines.push('  style: { stroke: ${accent}; stroke-width: 2 }');
      lines.push('}');
      lines.push('');
    }
  }

  for (const c of linked) {
    const anchor = (model.hops ?? []).find((h) => h.id === c.anchor);
    if (!anchor) continue;
    const band = companionBand(c);
    const label = `${c.subtitle ?? 'uses'} (${c.evidence})`;
    lines.push(`${anchor.lane}.${d2Id(anchor.id)} -> ${band}.${d2Id(c.id)}: "${esc(label)}" {`);
    lines.push('  style: { stroke-dash: 3 }');
    lines.push('}');
  }
  if (linked.length) lines.push('');

  const overflow = model.overflow?.count >= 1 ? model.overflow.count : 0;
  if (around.length || overflow) {
    lines.push('Release: "Also in this release" {');
    lines.push('  style: { stroke-dash: 4 }');
    for (const c of around) {
      lines.push(`  ${d2Id(c.id)}: "${esc(c.label)}"`);
    }
    if (overflow) lines.push(`  overflow: "+${overflow} more"`);
    lines.push('}');
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function main() {
  const args = process.argv.slice(2);
  const file = args.find((a) => !a.startsWith('--'));
  const outIdx = args.indexOf('--out');
  if (!file) {
    console.error('usage: node scripts/to-d2.mjs <model.json> [--out <file.d2>]');
    process.exit(1);
  }
  const model = JSON.parse(readFileSync(file, 'utf8'));
  const d2 = toD2(model);
  if (outIdx !== -1 && args[outIdx + 1]) {
    writeFileSync(args[outIdx + 1], d2);
    console.error(`wrote ${args[outIdx + 1]}`);
  }
  process.stdout.write(d2);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
